import { artifacts, network } from "hardhat";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const GENERATED_FILE_PATH = path.join(
  process.cwd(),
  "src",
  "lib",
  "generated",
  "receiptuary.generated.ts",
);

/**
 * Maps chain IDs to frontend network keys used by explorer and wallet helpers.
 */
function getNetworkNameFromChainId(chainId: number): string {
  switch (chainId) {
    case 8453:
      return "base";
    case 84532:
      return "baseSepolia";
    case 31337:
      return "hardhat";
    default:
      return `chain-${chainId}`;
  }
}

function validateFeeConfigForNetwork(
  networkName: string,
  feeTokenAddress: string,
) {
  const normalizedToken = feeTokenAddress.toLowerCase();
  const mainnetUsdc = "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913";

  if (networkName === "baseSepolia" && normalizedToken === mainnetUsdc) {
    throw new Error(
      "Deploy guard: Base Sepolia deploy is using Base mainnet USDC token address. Set USDC_TOKEN_ADDRESS to Sepolia USDC before deploying.",
    );
  }
}

async function syncFrontendContractConfig(
  address: string,
  networkName: string,
) {
  const artifact = await artifacts.readArtifact("Receiptuary");
  /**
   * The generated module is consumed by the frontend for deployed address and ABI.
   */
  const generatedSource = `/* AUTO-GENERATED by scripts/deploy.ts */\n\nexport const DEPLOYED_NETWORK = "${networkName}";\nexport const DEPLOYED_CONTRACT_ADDRESS = "${address}" as const;\n\nexport const DEPLOYED_RECEIPTUARY_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;

  await mkdir(path.dirname(GENERATED_FILE_PATH), { recursive: true });
  await writeFile(GENERATED_FILE_PATH, generatedSource, "utf8");
}

async function main() {
  /**
   * Uses explicit env variables so production values are never hardcoded.
   */
  const feeTokenAddress = process.env.USDC_TOKEN_ADDRESS?.trim();
  const feeRecipientAddress = process.env.RECEIPTUARY_FEE_RECIPIENT?.trim();
  const feeAmountRaw = process.env.RECEIPTUARY_FEE_AMOUNT?.trim();

  if (!feeTokenAddress || !feeRecipientAddress || !feeAmountRaw) {
    throw new Error(
      "Missing deploy env vars: USDC_TOKEN_ADDRESS, RECEIPTUARY_FEE_RECIPIENT, RECEIPTUARY_FEE_AMOUNT",
    );
  }

  if (!/^\d+$/.test(feeAmountRaw)) {
    throw new Error("RECEIPTUARY_FEE_AMOUNT must be an integer string");
  }

  const feeAmount = BigInt(feeAmountRaw);
  const { ethers } = await network.create();
  const providerNetwork = await ethers.provider.getNetwork();
  const deployedNetworkName = getNetworkNameFromChainId(
    Number(providerNetwork.chainId),
  );
  validateFeeConfigForNetwork(deployedNetworkName, feeTokenAddress);

  /**
   * Constructor receives fee config once, then generated frontend config is synced.
   */
  const contract = await ethers.deployContract("Receiptuary", [
    feeTokenAddress,
    feeRecipientAddress,
    feeAmount,
  ]);
  await contract.waitForDeployment();

  const deployedAddress = await contract.getAddress();
  const deploymentTx = contract.deploymentTransaction();
  const deploymentReceipt = deploymentTx
    ? await ethers.provider.getTransactionReceipt(deploymentTx.hash)
    : null;
  await syncFrontendContractConfig(deployedAddress, deployedNetworkName);

  console.log("Receiptuary deployed:", deployedAddress);
  if (deploymentTx) {
    console.log("Deployment tx:", deploymentTx.hash);
  }
  if (deploymentReceipt) {
    console.log("Deployment block:", deploymentReceipt.blockNumber);
  }
  console.log("Synced frontend config:", GENERATED_FILE_PATH);

  const isMainnetDeploy = deployedNetworkName === "base";
  const frontendAddressKey = isMainnetDeploy
    ? "NEXT_PUBLIC_RECEIPTUARY_CONTRACT_ADDRESS"
    : "NEXT_PUBLIC_DEMO_RECEIPTUARY_CONTRACT_ADDRESS";
  const frontendBlockKey = isMainnetDeploy
    ? "NEXT_PUBLIC_RECEIPTUARY_DEPLOYMENT_BLOCK"
    : "NEXT_PUBLIC_DEMO_RECEIPTUARY_DEPLOYMENT_BLOCK";
  const checklistCommand = isMainnetDeploy
    ? "npm run migration:v2:base:mainnet"
    : "npm run migration:v2:base:sepolia";

  console.log("V2 migration next steps:");
  console.log(`1) Set ${frontendAddressKey}=${deployedAddress}`);
  if (deploymentReceipt) {
    console.log(`2) Set ${frontendBlockKey}=${deploymentReceipt.blockNumber}`);
  } else {
    console.log(`2) Set ${frontendBlockKey}=<deployment_block_number>`);
  }
  console.log("3) Restart app and run: npm run test:app:smoke");
  console.log(`4) Full checklist: ${checklistCommand}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
