import { artifacts, network } from "hardhat";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const GENERATED_FILE_PATH = path.join(
  process.cwd(),
  "src",
  "lib",
  "generated",
  "receiptuary.generated.ts",
);

function getNetworkNameFromChainId(chainId: number): string {
  switch (chainId) {
    case 8453:
      return "base";
    case 84532:
      return "baseSepolia";
    case 31337:
      return "hardhat";
    default:
      return `chain-${chainId}`;
  }
}

async function syncFrontendContractConfig(
  address: string,
  networkName: string,
) {
  const artifact = await artifacts.readArtifact("Receiptuary");
  const generatedSource = `/* AUTO-GENERATED by scripts/deploy.ts */\n\nexport const DEPLOYED_NETWORK = "${networkName}";\nexport const DEPLOYED_CONTRACT_ADDRESS = "${address}" as const;\n\nexport const DEPLOYED_RECEIPTUARY_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;

  await mkdir(path.dirname(GENERATED_FILE_PATH), { recursive: true });
  await writeFile(GENERATED_FILE_PATH, generatedSource, "utf8");
}

async function main() {
  const feeTokenAddress = process.env.USDC_TOKEN_ADDRESS?.trim();
  const feeRecipientAddress = process.env.RECEIPTUARY_FEE_RECIPIENT?.trim();
  const feeAmountRaw = process.env.RECEIPTUARY_FEE_AMOUNT?.trim();

  if (!feeTokenAddress || !feeRecipientAddress || !feeAmountRaw) {
    throw new Error(
      "Missing deploy env vars: USDC_TOKEN_ADDRESS, RECEIPTUARY_FEE_RECIPIENT, RECEIPTUARY_FEE_AMOUNT",
    );
  }

  if (!/^\d+$/.test(feeAmountRaw)) {
    throw new Error("RECEIPTUARY_FEE_AMOUNT must be an integer string");
  }

  const feeAmount = BigInt(feeAmountRaw);
  const { ethers } = await network.create();
  const providerNetwork = await ethers.provider.getNetwork();
  const deployedNetworkName = getNetworkNameFromChainId(
    Number(providerNetwork.chainId),
  );
  const contract = await ethers.deployContract("Receiptuary", [
    feeTokenAddress,
    feeRecipientAddress,
    feeAmount,
  ]);
  await contract.waitForDeployment();

  const deployedAddress = await contract.getAddress();
  await syncFrontendContractConfig(deployedAddress, deployedNetworkName);

  console.log("Receiptuary deployed:", deployedAddress);
  console.log("Synced frontend config:", GENERATED_FILE_PATH);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
